version: '3.1'
services:
  db:
    image: postgres
    ports:
      - 0.0.0.0:5432:5432
    environment:
      POSTGRES_USER: squad
      POSTGRES_PASSWORD: dot
    volumes:
      - ../data:/data_csv

  adminer:
    image: adminer
    ports:
      - 8080:8080
